#!/usr/bin/python3
#F = [l for l in open("T", "r").readlines()]
F = [l for l in open("CAVE", "r").readlines()]
D = "RDLU"
O = [(0, 1), (1, 0), (0, -1), (-1, 0)]
P = F[len(F)-1].strip()
F = F[:len(F)-2]
X = max(map(len, F))-1
Y = len(F)
for i in range(Y):
    F[i] = F[i].strip("\n") + " "*X
pi = 0
x = F[0].index(".")
y = 0
d = 'R'
while pi < len(P):
    if P[pi].isdigit():
        s = pi
        while pi < len(P) and P[pi].isdigit():
            pi += 1
        v = int(P[s:pi])
        for _ in range(v):
            ny = (y + O[D.index(d)][0]) % Y
            nx = (x + O[D.index(d)][1]) % X
            while F[ny][nx] == ' ':
                ny = (ny + O[D.index(d)][0]) % Y
                nx = (nx + O[D.index(d)][1]) % X
            if F[ny][nx] == '#':
                break
            y = ny
            x = nx
    else:
        d = D[(D.index(d) + (1 if P[pi] == 'R' else -1)) % len(D)]
        pi += 1
print("41", (y + 1) * 1000 + (x + 1) * 4 + D.index(d))

print("42", 2)
