#!/usr/bin/python3
X = 0
Y = 0
S = []
for l in [l.strip() for l in open("SAND", "r").readlines()]:
    T = []
    for p in l.split("->"):
        (x,y) = p.strip().split(',')
        x, y = int(x), int(y)
        T.append([x,y])
        if x > X:
            X = x
        if y > Y:
            Y = y
    S.append(T)
F = [0]*(Y+3)
for i in range(len(F)):
    F[i] = [0]*(X+1+Y+1)
def n(p, e):
    if p[0] == e[0]:
        if e[1] > p[1]:
            p[1] += 1
        else:
            p[1] -= 1
    else:
        if e[0] > p[0]:
            p[0] += 1
        else:
            p[0] -= 1
for t in S:
    p = t[0]
    for i in range(1, len(t)):
        e = t[i]
        while (p != e):
            F[p[1]][p[0]] = 1
            n(p, e)
        F[p[1]][p[0]] = 1
        p = e
done = False
def drop(p, limit=True):
    global done
    if (limit and p[1] > Y) or F[p[1]][p[0]] > 0:
        done = True
        return False
    if p[1]>Y+1:
        print(p)
    if F[p[1]+1][p[0]] < 1:
        p[1] += 1
    elif F[p[1]+1][p[0]-1] < 1:
        p[1] += 1
        p[0] -= 1
    elif F[p[1]+1][p[0]+1] < 1:
        p[1] += 1
        p[0] += 1
    else:
        F[p[1]][p[0]] = 2
        return False
    return True
I = -1
while not done:
    I += 1
    p = [500, 0]
    while drop(p):
        pass
print("27", I)

for l in F:
    for i in range(len(l)):
        if l[i] == 2:
            l[i] = 0
F[Y+2] = [1]*(X+1+Y+1)
done = False
I = -1
while not done:
    I += 1
    p = [500, 0]
    while drop(p, False):
        pass
print("28", I)
