#!/usr/bin/python3
r  = [l.strip() for l in open("ROCKS", "r").readlines()][0]
ri = 0
# r = ">>><<><>><<<>><>>><<<>>><<<><<<>><>><<>>"
B = [["####"], [" # ", "###", " # "], ["###", "  #", "  #"], ["#", "#", "#", "#"], ["##", "##"]]
bi = 0
H = 0
F = ["#"*9]
for i in range(1, 100000000):
    F.append("#" + (" "*7) + "#")
def C(b, x, y):
    for i, Y in enumerate(b):
        for j in range(len(Y)):
            if Y[j] == "#" and F[y + i][x + j] == "#":
                return True
    return False
#for _ in range(2022):
#for _ in range(50455):
#for _ in range(13345):
Z = len(r)*len(B)
O = 0
P1 = 0
for _ in range(2022):
# for z in range(Z * 20):
    b = B[bi]
    bi = (bi + 1) % len(B)
    x = 3
    y = H + 4
    while True:
        if r[ri] == ">":
            if not C(b, x + 1, y):
                x = x + 1
        else:
            if not C(b, x - 1, y):
                x = x - 1
        ri = (ri + 1) % len(r)
        if not C(b, x, y - 1):
            y = y - 1
        else:
            break
    for i, Y in enumerate(b):
        for j in range(len(Y)):
            if Y[j] == "#":
                F[y + i] = F[y + i][:(x + j)] + "#" + F[y + i][(x + j + 1):]
    H = max(H, y + len(b) - 1)
    #if z % Z == Z-1:
    #    print(H - O)
    #    O = H
    #if z == 2021:
    #    P1 = H
    #    break
print("33", H)

C = len(r)*5
M = int(1000000000000 / C)
R = 1000000000000 % C
P = 78498
print(C, M, R, P)

print("34", M * P + 20774)

print(308 + 300 * (5000000000 - 1))

print(int(1000000000000/200/7) * 2120 + 308 + 300)
print(1000000000000 % 7)


    
